# 错误处理

## 在error中携带堆栈信息

  使用这个库：github.com/pkg/errors。

  用 `Wrap` 来携带堆栈信息，用 `fmt.Printf("%+v",err)` 来打印堆栈信息。

  用 `WithMessage` 来携带更多信息。

## go 1.13

 go 1.13后，用  `fmt.Errorf("err: %w", err)` 来携带更多信息，类似于 github.com/pkg/errors库中的`WithMessage`。可以使用 `errors.Is` 来判断错误，用 `errors.As` 来获取错误。但仍无法在error中获取堆栈信息。

## 原则

- 如果需要用到函数的返回值，一定要先判断错误。

- 每一个错误都只能处理一次。打印日志和返回错误都算处理过了。

- 在基础库、框架库中，直接return错误。

- 在应用层中调用底层时，使用`errors.Wrap`来处理错误，保存当前堆栈信息传给调用者。

- 调用包内的其余函数，直接返回错误。

- 最上层可以通过`fmt.Printf("%+v",err)`来打印堆栈信息。

- 最上层返回给用户的错误一定得是可读的。
